// Generated by CoffeeScript 1.3.1

$(document).ready(function() {
  var audioCtx, xhr;
  audioCtx = new webkitAudioContext();
  xhr = new XMLHttpRequest();
  xhr.open("GET", "/audio/41455__sandyrb__3auc-ir-combi-processed-001.wav", true);
  xhr.responseType = "arraybuffer";
  xhr.onload = function(e) {
    var buf, canvasElement, waveformRenderer;
    buf = audioCtx.createBuffer(xhr.response, false);
    canvasElement = document.getElementById("waveform");
    return waveformRenderer = new audioOnCanvas.WaveformRenderer({
      canvasElement: canvasElement,
      buffer: buf
    });
  };
  return xhr.send();
});
