// Generated by CoffeeScript 1.3.1
var audioOnCanvas;

audioOnCanvas = (typeof exports !== "undefined" && exports !== null) && this || (this.audioOnCanvas = {});

/*
#   @class  Used for generating a waveform inside a canvas
#           element.
*/


audioOnCanvas.WaveformRenderer = (function() {

  WaveformRenderer.name = 'WaveformRenderer';

  /*
    # @constructor
    #
    # @param  canvasElement  The canvas element to draw the waveform on.
    # @param  samples  The
  */


  function WaveformRenderer(canvasElement, samples) {
    var canvasCtx, canvasHeight, canvasWidth, midHeight;
    this.canvasElement = canvasElement;
    this.samples = samples;
    canvasCtx = this.canvasElement.getContext("2d");
    canvasHeight = canvasCtx.canvas.clientHeight;
    canvasWidth = canvasCtx.canvas.clientWidth;
    midHeight = canvasHeight / 2.0;
  }

  return WaveformRenderer;

})();
